.netstandard 2.0 support, migrate to Visual Studio 2017
ilyabreev/Bia.Countries pull request #17
Opened 2017-10-01 17:53 UTC by tinohager

add .netstandard 2.0 support, migrate to Visual Studio 2017, optimize
gitignore

2017-10-04 18:21 UTC, ilyabreev requested changes

2017-10-04 18:21 UTC, ilyabreev commented on nuget deploy.cmd
> +forfiles /m *.nupkg /c "cmd /c C:\nuget\NuGet.exe push @FILE -ApiKey XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX -Source https://www.nuget.org/api/v2/package -Verbosity detailed"
I'm not sure if it is a good idea to include `nuget.exe` path in script.

2017-10-04 20:41 UTC, tinohager commented
i have change the script

2017-10-05 04:04 UTC, ilyabreev approved these changes

2017-10-05 04:04 UTC, merged

2017-10-05 04:04 UTC, ilyabreev commented
fixes #16